name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        with:
          publish: bun run release
        env:
          NPM_TOKEN: ${{ secrets.NPM_SECRET }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 